apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rust-sdk

commonLabels:
  app: rust-sdk
  app.kubernetes.io/managed-by: kustomize

configMapGenerator:
  - name: common
    literals:
      - INNGEST_SERVE_ORIGIN=https://rust-sdk.inngest.net
      - INNGEST_SIGNING_KEY=REPLACE_SIGNING_KEY
      - INNGEST_EVENT_KEY=REPLACE_EVENT_KEY

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - service.yaml
  - deployment.yaml
