[package]
name = "inngest_macros"
version = "0.0.1"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
typetag = "0.2"

syn = { version = "2.0", features = ["extra-traits"]  }
quote = "1.0"
